title: Security Things
email: matt@kollersecurity.com
#description: "A dark-themed blog where I share my thoughts on technology, coding, and more."
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mrkoller.github.io" # the base hostname & protocol for your site
twitter_username: mr_koller
github_username:  mrkoller

theme: minima
plugins:
  - jekyll-feed

# Minima theme specific
minima:
  skin: dark # Utilizing Minima's built-in dark theme
