name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Build and deploy
      uses: actions/deploy-pages@v4
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
